name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Publish to GitHub Packages
      run: ./gradlew :api:publish
      env:
        USERNAME: JanotLeLapin
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
